unit: base
name: "_{Starfinder}"
group: "_{Core Rulebook}"

form:
  - option: permission
    name: "_{Permission to Print}"
    unit: option/permission

require:
  - unit: defs/dcs
  - unit: defs/feats
  - unit: defs/anathema
  - unit: defs/weapons
  - unit: defs/focus
  - unit: defs/saves
  - unit: defs/animal
  - unit: defs/calcs
  - unit: defs/actions
  - unit: defs/reference
  
  - with: high-contrast
    unit: starfinder/high-contrast
  - with: large-print
    unit: starfinder/large-print
  - with: dyslexic
    unit: starfinder/dyslexic

inc:
  - at: '@permission'
    add:
      - hr:
      - h6: _{This document uses trademarks and/or copyrights owned by Paizo Publishing,
          LLC, which are used under Paizo's Community Use Policy. We are expressly
          prohibited from charging you to use or access this content. This document
          is not published, endorsed, or specifically approved by Paizo.}
      - p: paizo.com/licenses/communityuse
