# Copyright 2025 Marcus Downing
# This file is compliant with the Open Game License (OGL).
# See the text of the OGL within this repository.

unit: option/inventory/kit
name: "_{Inventory Kit}"
group: "_{Core Rulebook}"

inc:
  - at: '@inventory/kit'
    replace:
      -
