unit: option/inventory/half
in: option/inventory
name: "_{Inventory (half size)}"
group: "_{Core Rulebook}"

inc:
  - at: '@pages'
    add:
      - page: inventory
        name: "_{Inventory (half size)}"
        order: 15
        flex: true
        # landscape: true
        half: true
        contents:
          - g:
            contents:
              - layout: 2e
                contents:
                  - g:
                    contents:
                      - section: "_{Inventory}"
                        contents:
                          - list:
                            hr: true
                            contents:

                              - g:
                                contents:
                                  - zone: '@inventory/kit'
                                    contents:
                                      - list:
                                        hr: true
                                        contents:
                                          - list:
                                            flex: small
                                            zebra: true
                                            contents:
                                              - row:
                                                contents:
                                                  - field: inventory-kit
                                                    width: stretch
                                                    legend: "_{Kit}"
                                                  - field: inventory-kit-value
                                                    label: "_{Value}"
                                                  - field: inventory-kit-weight
                                                    label: "_{Weight}"
                                              - repeat: 2
                                                reduce: 1
                                                merge-bottom: true
                                                contents:
                                                  - field: inventory-kit-contents-#{i}
                                                    frame: none
                                                    width: stretch

                              - g:
                                contents:
                                  - list:
                                    zebra: true
                                    hr: true
                                    contents:
                                      - repeat: 2
                                        reduce: 1
                                        contents:
                                          - article:
                                            no-header-line: true
                                            header:
                                              - row:
                                                contents:
                                                  - field: inventory-item-#{i}
                                                    width: stretch
                                                    frame: none
                                                  - field: inventory-item-#{i}-value
                                                    frame: none
                                                  - field: inventory-item-#{i}-bulk
                                                    frame: none
                                            lines: 1
                                      - list:
                                        zebra: true
                                        collapse: true
                                        field_frame: none
                                        contents:
                                          - repeat: 6
                                            reduce: 2
                                            contents:
                                              - row:
                                                contents:
                                                  - field: inventory-#{i}
                                                    width: stretch
                                                  - field: inventory-#{i}-value
                                                  - field: inventory-#{i}-bulk
                                  # - row:
                                  #   contents:
                                  - field: bulk-total
                                    frame: left
                                    label: "_{Total bulk}"
                                    border: full
                                    control: weight
                                  - p: "_{10 light = 1 bulk}"

                              - g:
                                contents:
                                  - h5: "_{Backpack}"
                                  - list:
                                    zebra: true
                                    collapse: true
                                    field_frame: none
                                    contents:
                                      - repeat: 6
                                        reduce: 2
                                        contents:
                                          - row:
                                            contents:
                                              - field: inventory-backpack-#{i}
                                                width: stretch
                                              - field: inventory-backpack-#{i}-value
                                              - field: inventory-backpack-#{i}-bulk
                                  - row:
                                    contents:
                                      - field: weight-backpack-ignore
                                        control: value
                                        value: "-2"
                                        frame: none
                                        width: tiny
                                      - p: "_{Bulk}"
                                      - field: weight-backpack-total
                                        frame: left
                                        label: ""
                                        border: full
                                        control: weight

                              - g:
                                contents:
                                  - h5: "_{Expendables}"
                                  - list:
                                    zebra: true
                                    collapse: true
                                    field_frame: none
                                    merge-bottom: true
                                    contents:
                                      - repeat: 2
                                        contents:
                                          - row:
                                            contents:
                                              - field: expendable-#{i}
                                                width: stretch
                                              - field: expendable-#{i}-count
                                                frame: none
                                                control: checkgrid
                                                max: 20
                                                depth: 3

                              - g:
                                contents:
                                  - h5: "_{Money}"
                                  - field: money-platinum
                                    frame: left
                                    control: money
                                    label: "_{Platinum}"
                                    denomination: platinum
                                    digits: 7
                                    shift: 3
                                  - field: money-gold
                                    frame: left
                                    control: money
                                    label: "_{Gold}"
                                    denomination: gold
                                    digits: 8
                                    shift: 2
                                  - field: money-silver
                                    frame: left
                                    control: money
                                    label: "_{Silver}"
                                    denomination: silver
                                    digits: 9
                                    shift: 1
                                  - field: money-copper
                                    frame: left
                                    control: money
                                    label: "_{Copper}"
                                    denomination: copper
                                    digits: 10
                                  - field: money-total
                                    frame: left
                                    output: 'true'
                                    control: money
                                    legend: "_{Total}"
                                    denomination: copper
                                    digits: 10
                                    decimal: 1
                                  - p: "_{1000 coins = 1 bulk}"
                      - tail:

                  - g:
                    contents:
                      - section: "_{Invested Items}"
                        contents:
                          - list:
                            zebra: true
                            flex: true
                            hr: true
                            avoid-shade: true
                            contents:
                              - repeat: 10
                                reduce: 2
                                contents:
                                  - level: '#{i}'
                                    marker: ''
                                    contents:
                                      - article:
                                        lines: 1

                      - section: "_{Armour}"
                        contents:
                          - row:
                            layout: split
                            contents:
                              - field: armour
                                frame: none
                                size: large
                                width: stretch
                              - field: armour-bulk
                                label: "_{Bulk}"
                              - field: ac-armour-bonus
                                label: "_{AC Bonus}"
                                icon: armour
                                border: full
                              - field: ac-armour-potency
                                control: counter
                                label: "_{Potency}"
                          - row:
                            layout: split
                            contents:
                              - field: armour-cat
                                label: "_{Category}"
                                width: stretch
                              - field: armour-dex-cap
                                label: "_{DEX\nCap}"
                              - field: armour-str-rating
                                label: "_{STR\nRating}"
                              - field: armour-acp
                                label: "_{Check\nPenalty}"
                          - field: armour-properties
                            width: stretch
                            label: "_{Armour Traits}"
                            frame: annotation
                            repeat: 2
                            reduce: 1
                            merge-bottom: true

                      - section: "_{Shield}"
                        contents:
                          - row:
                            layout: split
                            contents:
                              - field: shield
                                frame: none
                                size: large
                                width: stretch
                              - field: shield-bulk
                                label: "_{Bulk}"
                              - field: shield-ac
                                label: "_{AC Bonus}"
                                icon: shield
                                border: full
                          - row:
                            contents:
                              - field: shield-hardness
                                label: "_{Hardness}"
                                width: large
                                suffix: "_{hp}"
                              - spacer:
                              - field: shield-bt
                                label: "_{Broken}"
                                suffix: "_{hp}"
                                prefix: "&le;"
                                width: large
                              - spacer:
                              - field: shield-hp
                                label: "_{Hit Points}"
                                icon: hp
                                border: full
                                width: large
                                suffix: "_{hp}"
                          - field: shield-properties
                            width: stretch
                            label: "_{Shield Traits}"
                            frame: annotation
                            repeat: 2
                            reduce: 1
                            merge-bottom: true

                      - tail:

