unit: option/inventory/full
in: option/inventory
name: "_{Inventory (full size)}"

inc:
  - at: '@pages'
    add:
      - page: inventory
        name: "_{Inventory (full size)}"
        order: 16
        flex: true
        contents:
          - layout: 2l
            contents:
              - g:
                contents:
                  - section: "_{Inventory}"
                    contents:
                      - list:
                        hr: true
                        contents:
                          - g:
                            contents:
                              - zone: '@inventory/kit'
                                contents:
                                  - list:
                                    flex: small
                                    zebra: true
                                    contents:
                                      - row:
                                        contents:
                                          - field: inventory-kit
                                            width: stretch
                                            legend: "_{Kit}"
                                          - field: inventory-kit-value
                                            label: "_{Value}"
                                          - field: inventory-kit-weight
                                            label: "_{Weight}"
                                          # - field: inventory-kit-checked
                                          #   control: checkbox
                                          #   label: "_{Ready}"
                                      - repeat: 4
                                        reduce: 2
                                        merge-bottom: true
                                        contents:
                                          - field: inventory-kit-contents-#{i}
                                            frame: none
                                            width: stretch
                          - g:
                            contents:
                              - row:
                                contents:
                                  - h5: "_{Items}"
                                  - spacer:
                                  - label: "_{Readied}"
                              - list:
                                zebra: true
                                hr: true
                                contents:
                                  - repeat: 2
                                    reduce: 1
                                    contents:
                                      - article:
                                        header:
                                          - row:
                                            contents:
                                              - field: inventory-item-large-#{i}
                                                width: stretch
                                                frame: none
                                              - field: inventory-item-large-#{i}-value
                                                frame: none
                                              - field: inventory-item-large-#{i}-weight
                                                frame: none
                                              - field: inventory-item-large-#{i}-checked
                                                frame: none
                                                control: checkbox
                                        lines: 1
                                  - list:
                                    zebra: true
                                    collapse: true
                                    field_frame: none
                                    contents:
                                      - repeat: 8
                                        reduce: 4
                                        contents:
                                          - row:
                                            contents:
                                              - field: inventory-item-#{i}
                                                width: stretch
                                              - field: inventory-item-#{i}-value
                                              - field: inventory-item-#{i}-weight
                                              - field: inventory-item-#{i}-checked
                                                frame: none
                                                control: checkbox
                              - row:
                                contents:
                                  - p: "_{10 light = 1 bulk}"
                                  - field: weight-total
                                    frame: left
                                    label: "Total weight"
                                    border: full
                                    control: weight

                          - g:
                            contents:
                              - h5: "_{Backpack}"
                              - list:
                                zebra: true
                                collapse: true
                                field_frame: none
                                contents:
                                  - repeat: 16
                                    reduce: 2
                                    contents:
                                      - row:
                                        contents:
                                          - field: inventory-backpack-#{i}
                                            width: stretch
                                          - field: inventory-backpack-#{i}-value
                                          - field: inventory-backpack-#{i}-weight
                                          # - field: inventory-#{i}-checked
                                          #   frame: none
                                          #   control: checkbox
                              - row:
                                contents:
                                  - field: weight-backpack-ignore
                                    control: value
                                    value: "-2"
                                    frame: none
                                    width: tiny
                                  - p: "_{bulk of items in backpack}"
                                  - spacer:
                                  - field: weight-backpack-total
                                    frame: left
                                    label: ""
                                    border: full
                                    control: weight

                          - g:
                            flex: tiny
                            contents:
                              - h5: "_{Expendables}"
                              - list:
                                zebra: true
                                collapse: true
                                field_frame: none
                                merge-bottom: true
                                contents:
                                  - repeat: 3
                                    contents:
                                      - row:
                                        contents:
                                          - field: expendable-#{i}
                                            width: stretch
                                          - field: expendable-#{i}-count
                                            frame: none
                                            control: checkgrid
                                            max: 20
                                            depth: 3

                          - g:
                            contents:
                              - row:
                                contents:
                                  - calc:
                                    output:
                                      field: encumberance
                                      label: "_{Encumberance}"
                                      suffix: "_{B}"
                                      width: large
                                    inputs:
                                      - span: "5 +"
                                      - field:
                                        ref: STR
                                        label: "_{STR}"
                                        underlay: "_{STR}"
                                        width: small
                                  - calc:
                                    optional: true
                                    output:
                                      field: encumberance-max
                                      label: "_{Carry Limit}"
                                      suffix: "_{B}"
                                      width: large
                                    inputs:
                                      - span: "10 +"
                                      - field:
                                        ref: STR
                                        label: "_{STR}"
                                        underlay: "_{STR}"
                                        width: small
                  - tail:

              - g:
                contents:
                  - layout: 2e
                    flex: huge
                    contents:
                      - g:
                        contents:
                          - g:
                            contents:
                              - section: "_{Armour}"
                                mark: armour
                                contents:
                                  - row:
                                    layout: split
                                    contents:
                                      - field: armour
                                        frame: none
                                        size: large
                                        width: stretch
                                      - field: armour-bulk
                                        label: "_{Bulk}"
                                  - row:
                                    contents:
                                      - field: armour-ac
                                        label: "_{AC Bonus}"
                                        icon: armour
                                        border: full
                                      - field: armour-potency
                                        control: icon
                                        label: "_{Potency}"
                                        icon: runes
                                      - field: armour-runes
                                        label: "_{Runes}"
                                        width: stretch
                                        align: center
                                  - row:
                                    layout: split
                                    contents:
                                      - field: armour-cat
                                        label: "_{Category}"
                                        width: stretch
                                      - field: armour-dex-cap
                                        label: "_{DEX\nCap}"
                                      - field: armour-str-rating
                                        label: "_{STR\nRating}"
                                      - field: armour-acp
                                        label: "_{Check\nPenalty}"
                                  - field: armour-properties
                                    width: stretch
                                    label: "_{Armour Traits}"
                                    repeat: 3
                                    reduce: 1
                                    merge-bottom: true

                              - section: "_{Shield}"
                                mark: shield
                                contents:
                                  - row:
                                    layout: split
                                    contents:
                                      - field: shield
                                        frame: none
                                        size: large
                                        width: stretch
                                      - field: shield-bulk
                                        label: "_{Bulk}"
                                  - row:
                                    contents:
                                      - field: shield-ac
                                        label: "_{AC Bonus}"
                                        icon: shield
                                        border: full
                                      - field: shield-hardness
                                        label: "_{Hardness}"
                                        width: large
                                        suffix: "_{hp}"
                                      # - spacer:
                                      - field: shield-bt
                                        label: "_{Broken}"
                                        suffix: "_{hp}"
                                        prefix: "&le;"
                                        width: large
                                      # - spacer:
                                      - field: shield-hp
                                        label: "_{Hit Points}"
                                        icon: hp
                                        border: full
                                        suffix: "_{hp}"
                                  - field: shield-properties
                                    width: stretch
                                    label: "_{Shield Traits}"
                                    repeat: 3
                                    reduce: 1
                                    merge-bottom: true

                              - tail:

                              - portrait: personal
                                overprint: true

                              - section: "_{Money}"
                                flex: none
                                contents:
                                  - g:
                                    blk: true
                                    contents:
                                      - field: money-platinum
                                        frame: left
                                        control: money
                                        label: "_{Platinum}"
                                        denomination: platinum
                                        digits: 6
                                        shift: 3
                                      - field: money-gold
                                        frame: left
                                        control: money
                                        label: "_{Gold}"
                                        denomination: gold
                                        digits: 7
                                        shift: 2
                                      - field: money-silver
                                        frame: left
                                        control: money
                                        label: "_{Silver}"
                                        denomination: silver
                                        digits: 8
                                        shift: 1
                                      - field: money-copper
                                        frame: left
                                        control: money
                                        label: "_{Copper}"
                                        denomination: copper
                                        digits: 9
                                      - field: money-total
                                        frame: left
                                        output: 'true'
                                        control: money
                                        legend: "_{Total}"
                                        denomination: copper
                                        digits: 9
                                        decimal: 1
                                  - p: "_{1000 coins = 1 bulk}"
                              - section: "_{Scrolls}"
                                flex: none
                                mark: scroll
                                contents:
                                  - list:
                                    merge-bottom: true
                                    zebra: true
                                    avoid-shade: true
                                    contents:
                                      - repeat: 6
                                        reduce: 1
                                        contents:
                                          - row:
                                            blk: false
                                            contents:
                                              - field: inventory-scrolls-#{i}
                                                frame: none
                                                width: stretch
                                              - field: inventory-scrolls-#{i}-use
                                                control: checkbox
                                                frame: none
                              - tail:

                      - g:
                        contents:
                          - section: "_{Invested Items}"
                            contents:
                              - list:
                                zebra: true
                                flex: true
                                avoid-shade: true
                                hr: true
                                contents:
                                  - repeat: 10
                                    contents:
                                      - level: '#{i}'
                                        marker: ''
                                        contents:
                                          - article:
                                            lines: 2
                                            show-level: true
                          - section: "_{Potions}"
                            flex: none
                            mark: potion
                            contents:
                              - list:
                                merge-bottom: true
                                zebra: true
                                avoid-shade: true
                                contents:
                                  - repeat: 11
                                    reduce: 2
                                    contents:
                                      - row:
                                        blk: false
                                        contents:
                                          - field: inventory-potion-#{i}
                                            width: stretch
                                            frame: none
                                          - field: inventory-potion-#{i}-count
                                            underlay: "#"
                                            frame: none
                                          - field: inventory-potion-#{i}-use
                                            frame: none
                                            control: checkgrid
                                            max: 6
                                            depth: 2
                          - tail:
