---
unit: base
name: "Dungeons & Dragons 5th Edition"

form:
  - option: permission
    name: "Permission to Print"
    unit: option/permission

inc:

  - at: '@permission'
    add:
      - hr:
      - h6: Dyslexic Character Sheets is unofficial Fan Content permitted under the Fan Content Policy.
          Not approved/endorsed by Wizards. Portions of the materials used are property of Wizards of the Coast. ©Wizards of the Coast LLC.
      - p: https://company.wizards.com/fancontentpolicy
